### ISSUE TITLE
 Failed to proxy [url] Error: socket hang up

### ISSUE THREAD

**Issue by codingjamee** [codingjamee/pruru_front#4]
상황정리 

1. 프론트 도커 파일로 컨테이너를 실행하였다 

프론트의 이미지는 proxy를 사용하고 있고, 

통신을 할 때 내부 DNS주소로 변경하여 통신을 시도하였다

next.config.mjs파일

```
 rewrites: async () => ({
    beforeFiles: [
      {
        source: '/api/:path((?!auth).*)',
        destination: `${process.env.NEXT_PUBLIC_BASE_URL}/api/:path*`,
      },
```

.env파일 중 일부

`NEXT_PUBLIC_BASE_URL='http://host.docker.internal:5000'
`

2. 백엔드 도커 컴포즈 파일로 두개의 컨테이너를 실행 하여 mysql 컨테이너와 node컨테이너 간의 통신을 할 수 있게 하였다. 

백엔드에서는 두개의 컨테이너간 통신이 잘 이루어 지고 있다.

```
    networks:
      - refrigeratornetwork
```

그러나 백-프간의 통신이 원활하게 이뤄지지 않았다. 

## 원인 분석

1. 내부 네트워크 연결이 되지 않았기 때문에 ? 
docker network connect [네트워크명] [containerId]

my-refrigerator-back_refrigeratornetwork에 연결된 모습
<img width="298" alt="download (1)" src="https://github.com/codingjamee/pruru_front/assets/99540667/b61053d7-0e18-44e1-b9bf-b675a8853b95">

그러나 여전히 통신이 되지 않았다. 

2. 환경변수를 가져오지 못하는 문제 
container를 demon으로 실행할 때 옵션으로 환경변수를 넣어주기 

`docker run -it --env-file ./.env -d --name "[컨테이너명]" -p 외부포트:내부포트 [image명]
`

컨테이너 inspect로 확인한 모습 
![image](https://github.com/codingjamee/pruru_front/assets/99540667/e839c543-8841-42dd-8164-53ba5f53010d)

이경우 보안상 문제가 될 수 있으나, 

현업에서는 docker hub같은 공개적인 플랫폼을 사용하는 것이 아니기 때문에 괜찮(?)음

그러나 이렇게 해도 통신문제 해결되지 않음

에러화면 
![image](https://github.com/codingjamee/pruru_front/assets/99540667/bfea133a-7dd2-4bee-ae9f-795e248b76aa)

3. 컨테이너의 DNS설정
proxy로 설정할 때 내부 

http://host.docker.internal:5000/ 로 하면 내부 DNS로 연결 할 수 있다고 해서 

연결했으나 연결되지 않음 

컨테이너 명 또는 고정 IP로 연결하면 된다고 해서 

컨테이너 명으로 설정해봄

 동일한 네트워크에 세개의 컨테이너가 연결되어있는것 확인 

`docker network inspect my-refrigerator-back_refrigeratornetwork
`
![image](https://github.com/codingjamee/pruru_front/assets/99540667/41426f10-5bce-456f-bcc3-c4bc639a2d47)

그러나 여전히 에러 

4. docker-compose로 함께 빌드하여 네트워크 연결 
추가된 docker-compose file 

```
 pruru-front:
    build: ../pruru_front # pruru-front의 Dockerfile 위치
    ports:
      - "80:80" # pruru-front가 사용할 포트 (예시)
    networks:
      - refrigeratornetwork
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL} # 백엔드 서비스 URL 예시
    env_file:
      - .env
```

그러나 동일한 에러 문구 뜸
